- name: get the metadata
  hosts: localhost
  tasks:
    - name: Get metadata
      uri:
        url: "http://169.254.169.254/latest/meta-data/"
        return_content: yes
      register: METADATA
    - debug:
        msg: "{{METADATA.content}}"
    # include the below if we need to send this metadata to email
    - include: email.yml
  
